services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    restart: always
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - ZINC_ADMIN_USER=${ZINC_ADMIN_USER}
      - ZINC_ADMIN_PASSWORD=${ZINC_ADMIN_PASSWORD}

  zincsearch:
    container_name: zincsearch
    image: public.ecr.aws/zinclabs/zincsearch:latest  
    volumes:
      - ./zincsearch/data:/data
    environment:
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=${ZINC_ADMIN_USER}
      - ZINC_FIRST_ADMIN_PASSWORD=${ZINC_ADMIN_PASSWORD}
    ports:
      - 4080:4080
    restart: always